pub struct MysqlSchema {}

// We can replace this module with https://github.com/SeaQL/sea-schema.

impl MysqlSchema {
    /// Gets table schema for the given table path. It will request to MySQL server
    /// by running `SHOW CREATE TABLE` if cache missed.
    pub fn get_table_schema() {
        todo!()
    }
}

/// The definition of a table, generated by 'DESC <table>'
pub struct MysqlTableDef {
    pub table_name: String,
    pub columns: Vec<MysqlColumnDef>,
    pub primary_keys: Vec<String>,
}

pub struct MysqlColumnDef {}
