[workspace]
members = [
    "chgcap",
    "chgcap-mysql",
    "chgcap-mysql/test-utils",
    "chgcap-mysql/ddl-parser",
]

[workspace.package]
homepage = ""
keywords = ["cdc"]
license = "Apache-2.0"
repository = "https://github.com/neverchanje/chgcap-rs"
